
import Link from 'next/link'
import Header from '../../../components/header';
import JobFeed from '../../../features/jobs/job-feed';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Page() {
  return (
    <>
    <Header />
    <div className="bg-dark">
      <div className="py-5 container-fluid d-flex justify-content-center align-items-center">
        <div>
          <p class="h2 text-center text-light">Modeling Jobs</p>
          <div class="text-center">
            <Link href="/job/create" class="btn btn-primary">Post a Job</Link>
          </div>
        </div>
      </div>
      <div className="container">
        {<JobFeed />}
      </div>
    </div>
    </>
  )
}
